# documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel
latex: true
warnings_are_errors: false

cache:
  - packages
  - ccache

r_binary_packages:
  - magrittr
  - rlang

r_packages:
  - bindrcpp
  - purrr
  - dplyr
  - stringr

r_github_packages:
  - jimhester/lintr

notifications:
  email:
  on_success: change
  on_failure: change

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'