# documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - release
  - devel

sudo: required
cache: packages
bioc_required: true
warnings_are_errors: false

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_binary_packages:
  - magrittr

r_packages:
  - rlang
  - bindrcpp
  - purrr
  - dplyr
  - stringr

notifications:
  email:
  on_success: change
  on_failure: change

